spring:
  application:
    name: jpa-security
  datasource:
    url: jdbc:postgresql://localhost:5433/testdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true